minimal-version = 0.1

[build.godot]
version = "4.5"

[targets.loader]
path = "."
default = true
requirements = ["pack_A", "pack_B"]

[targets.pack_A]
path = "packs/pack_A"
out = "packs"
godot = { export_pack = true }

[targets.pack_B]
path = "packs/pack_B"
out = "packs"
godot = { export_pack = true }
